name: Verible formatting
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: chipsalliance/verible-formatter-action@main
      with:
        files: ./property/**/*.{v,sv,vh,svh,sva}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        parameters: "--flagfile=.verible-format-flags"
        fail_on_formatting_suggestions: true